### ISSUE TITLE
BUG? not compatible with https://github.com/ossrs/srs

### ISSUE THREAD

**Issue by jinleileiking** [yutopp/go-rtmp#51]
ffmpeg -> srs -> go-rtmp server demo

failed with handshake
<img width="590" alt="image" src="https://user-images.githubusercontent.com/93968/215696759-d078e4f5-1d23-492e-b549-479fe60cf406.png">

[srs](https://github.com/ossrs/srs):
<img width="608" alt="image" src="https://user-images.githubusercontent.com/93968/215696846-fe8d214a-c9af-43d6-ad64-7ace9c502874.png">

**Comment by yutopp** [comment]
It should have been resolved in #52.
