### ISSUE TITLE
is it possible to publish audio data every 0.5 second?

### ISSUE THREAD

**Issue by ohjiwoo123** [yutopp/go-rtmp#54]
original code of rtmp OnAudio function like this, 
```
func (h *Handler) OnAudio(timestamp uint32, payload io.Reader) error {
	var audio flvtag.AudioData
	if err := flvtag.DecodeAudioData(payload, &audio); err != nil {
		return err
	}

	flvBody := new(bytes.Buffer)
	if _, err := io.Copy(flvBody, audio.Data); err != nil {
		return err
	}
	audio.Data = flvBody
	_ = h.pub.Publish(&flvtag.FlvTag{
		TagType:   flvtag.TagTypeAudio,
		Timestamp: timestamp,
		Data:      &audio,
	})

	return nil
}
```

and i want to chage the code that publish audio data every 0.5 second 
so trying like this 

```
func (h *Handler) OnAudio(timestamp uint32, payload io.Reader) error {

	var audio flvtag.AudioData
	if err := flvtag.DecodeAudioData(payload, &audio); err != nil {
		return err
	}
       // if flag == true, startTimeStamp Control
	if h.Flag == true {
		h.startTimeStamp = timestamp
		//h.Buf = new(bytes.Buffer)
		h.Buf.Reset()
	}
	h.Flag = false

	buf := new(bytes.Buffer)
	if _, err := io.Copy(buf, audio.Data); err != nil {
		return err
	}

	if audio.AACPacketType == 0 {
		audio.Data = buf
		tag := &flvtag.FlvTag{
			TagType:   flvtag.TagTypeAudio,
			Timestamp: h.startTimeStamp,
			Data:      &audio,
		}
		timestamp, (timestamp - h.startTimeStamp), buf.Len())
		_ = h.pub.Publish(tag)
		h.Flag = true
		return nil
	}

	h.Buf.Write(buf.Bytes())

        // collect audio data into h.Buf and then publish every 0.5 seconds
	if timestamp-h.startTimeStamp >= 500 {
		h.lastTimeStamp = timestamp
		audio.Data = h.Buf
		tag := &flvtag.FlvTag{
			TagType:   flvtag.TagTypeAudio,
			Timestamp: h.startTimeStamp,
			Data:      &audio,
		}

		_ = h.pub.Publish(tag)
		h.Flag = true
	}

	return nil
}
```
when i check the audio data size There is no Data loss but Audio Data is Broken. 
Is there any problem with my code?

**Comment by yutopp** [comment]
Hello!

If you want to set the transmission interval to every 0.5 seconds, instead of buffering and concatenating the audio binary data, you might consider queuing each payload as an &flvtag.FlvTag and then sending them. By grouping them together in the FLV container, rather than in the codec binary, it should be possible to achieve proper playback.

**Comment by ohjiwoo123** [comment]
Thank you bro!
Your idea is correct, using queue, it works well. 
additionally, I wonder that this package has audio latency? I think there is one or two seconds audio latency. 
In my case, publisher : OBS, subscriber, VLC Player. 
if i want to fix about audio latency, what shoud I do?

**Comment by yutopp** [comment]
I do not intend to implement any delay.

First, you may want to create a pass-through handler that does nothing, and while printing the FLV timestamps on the server's receiving side, also check the timestamps on the subscriber side. On the subscriber side, tools like ffprobe -show_frames can be helpful.

If there is a difference between the timestamps on the publisher side and the server's receiving side, it might be effective to reset the timestamps.

I can provide further assistance if you can share a minimal reproducible code and test data.
